name: Frontend
on:
  push
jobs:
  frontend_deployment:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint